project:
  type: website

website:
  sidebar:
    title: "Apuntes FullStack"
    search: true
    contents:
      - text: "General"
        href: index.qmd        
      - text: "Spring Boot"
        contents: 
          - text: "Introduction"
            href: 01-spring-boot/index.qmd
          - text: "Annotations"
            href: 01-spring-boot/annotations.qmd  
          - text: "UML"
            href: 01-spring-boot/uml.qmd
          - text: "Request-Response Cycle"
            href: 01-spring-boot/request-response-cycle.qmd  
          - text: "Relationships"
            href: 01-spring-boot/relationship.qmd  
          - text: "Classes"
            href: 01-spring-boot/classes.qmd  
      - text: "React"   
        contents:  
          - text: "Introduction"
            href: 02-react/index.qmd 
          - text: "Components"
            href: 02-react/components.qmd  
          - text: "Hooks"
            href: 02-react/hooks.qmd
          - text: "Functions"
            href: 02-react/functions.qmd    
          - text: "HTML"
            href: 02-react/html.qmd            
      - text: "APIs"  
        href: 03-api/index.qmd
      - text: "Data Bases"   
        contents:
          - text: "Introduction"
            href: 04-data-base/index.qmd
          - text: "SQL"
            href: 04-data-base/sql.qmd
          - text: "PostgreSQL"
            href: 04-data-base/postgresql.qmd  
      - text: "Tests"  
        contents: 
          - text: "Introduction"
            href: 05-tests/index.qmd
          - text: "JUnit"
            href: 05-tests/junit.qmd  
      - text: "Documentation"
        href: 06-documentation/index.qmd
      - text: "Tools"
        href: 07-tools/index-tools.qmd  
      - text: "Cheat Sheet"
        href: cheatSheet.qmd
      - text: "Notes"
        href: notes.qmd  
  page-footer:
    right: "© 2024 Alberte - Apuntes de Desarrollo Web"

format:
  html:
    theme: darkly  # https://quarto.org/docs/output-formats/html-themes.html
    css: styles.css
    toc: true      # Tabla de contenido automática
    mainfont: "Helvetica"
    breadcrumbs: true
