---
title: "GENERAL"
---

# Main Index
---

## 1. Spring boot
   1.1. Index
   1.2. UML
   1.3. Request-Response Cycle
## 2. React
   2.1. Index
## 3. API
   3.1. Index
## 4. Data Bases
   4.1. Index
## 5. Tests
   5.1. Index
## 6. Documentation
   6.1. Index
## 7. Tools
   7.1. Index  

# Notas

## Commit codes:
- `doc:` Documentación tipo resources
- `proj:` Management como scripts y demás.
- `pra:` Prácticas.
- `feat:` Código de proyecto (Creando un controller, query, service...)
- `fix:` Corrección de errores.

## Pareto 
- Regla 80/20. El 80% de los resultados provienen del 20% de las causas.

::: {.callout-note title="Antipareto"}
- Equipos altamente colaborativos 
- Distribución de ingresos equitativa 
- Comunidades pequeñas
:::
---



## SSR (Server-Side Rendering) y CSR (Client-Side Rendering)

| Característica          | SSR (Server-Side Rendering)       | CSR (Client-Side Rendering)       |
|-------------------------|-----------------------------------|-----------------------------------|
| **Renderizado**          | En el servidor                   | En el navegador                   |
| **SEO**                 | Mejor                            | Más complicado                    |
| **Carga inicial**       | Más rápida                       | Más lenta                         |
| **Interactividad**      | Limitada (requiere JS adicional) | Muy fluida                        |
| **Carga del servidor**  | Mayor                            | Menor                             |
| **Uso típico**          | Páginas con contenido estático   | Aplicaciones web dinámicas (SPA)  |

